languague: node_js
node_js:
- '14'
git:
  depth: 3
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - felagossanchez@gmail.com
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: test
    script: npm run test
  - stage: build
    script: npm run build
deploy:
  provider: heroku
  skip-clean: true
  kepp-history: true
  api_key:
    secure: $HEROKU_TOKEN
  app: movie-db-web
  on:
    repo: felagos/moviedb
