export const GENRE_TYPES = {
	LOAD: "LOAD_GENRE"
};

export const MOVIE_TYPES = {
	LOAD_POPULAR: "LOAD_POPULAR_MOVIES",
	LOAD_UPCOMING: "LOAD_UPCOMING_MOVIES",
	LOAD_TRENDING: "LOAD_TRENDING_MOVIES"
};
