name: "Build Release"

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Store node_modules in cache
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci


  test:
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Restore node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.5
        with:
          run: npm run test

  build:
    needs: [ prepare ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Restore node_modules from cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Build application
        run: |
          npm run build
