name: moviedb

on:
  push:
    branches: [ master ]

jobs:
  setup-app:
    runs-on: ubuntu-latest
    name: setup-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14' 
      - name: Install Packages
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
  test-app:
    runs-on: ubuntu-latest
    needs: setup-app
    name: test-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14' 
      - name: Run install
        if: steps.cacheDependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test app
        run: npm run test
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Test E2E
        run: npm run e2e:ci
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  deploy-app:
    runs-on: ubuntu-latest
    needs: test-app
    name: deploy-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Run install
        if: steps.cacheDependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run build
        run: CI=true && npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: copy file via ssh key
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          rmRemote: true
          recursive: true
          local: "./build"
          remote: ${{ secrets.FOLDER_DESTINATION }}
          concurrency: 10
