name: moviedb

on:
    push:
        branches: [ master ]

jobs:
  setup-app:
    runs-on: ubuntu-latest
    name: setup-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Packages
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
  test-app:
    runs-on: ubuntu-latest
    needs: setup-app
    name: test-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Run install
        if: steps.cacheDependencies.outputs.cache-hit != 'true'
        run: yarn
      - name: Test app
        run: yarn test
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Test E2E
        run: yarn e2e:ci
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  deploy-app:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
        - name: Set Env Vars on Vercel Project
          uses: dkershner6/vercel-set-env-action@v1
          with:
            token: ${{ secrets.VERCEL_TOKEN }}
            teamId: ${{ secrets.VERCEL_TEAM_ID }}
            projectName: moviedb
            envVariableKeys: REACT_APP_API_KEY,REACT_APP_API_URL
          env:
             REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
             TARGET_REACT_APP_API_URL: production
             PLAIN_REACT_APP_API_URL: plain

             REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
             TARGET_REACT_APP_API_KEY: production
             PLAIN_REACT_APP_API_KEY: plain
        - name: deploy site to vercel
          uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
            github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
            vercel-args: '--prod' #Optional
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
