name: moviedb

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Run install
      run: npm ci
    - name: Run build
      run: npm run build
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
    - name: Show files
      run: ls -a ./build     
    - name: Run test
      run: npm run test
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "build/,css/,static/"
        target: ${{ secrets.FOLDER_DESTINATION }}
        strip_components: 3 # this is important
